/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

/* This file is auto-generated by a vitest globalSetup hook */
import { beforeEach, vi } from 'vitest';

import product from '../../product.json' with { type: 'json' };

const namespaceMocks = {} as Record<string, Record<string, unknown>>;
namespaceMocks.extensions = {};
namespaceMocks.extensions.getExtension = vi.fn();
namespaceMocks.extensions.all = vi.fn();
namespaceMocks.extensions.onDidChange = vi.fn();
namespaceMocks.commands = {};
namespaceMocks.commands.registerCommand = vi.fn();
namespaceMocks.commands.executeCommand = vi.fn();
namespaceMocks.provider = {};
namespaceMocks.provider.createProvider = vi.fn();
namespaceMocks.provider.onDidUpdateProvider = vi.fn();
namespaceMocks.provider.onDidUpdateContainerConnection = vi.fn();
namespaceMocks.provider.onDidUpdateKubernetesConnection = vi.fn();
namespaceMocks.provider.onDidUnregisterContainerConnection = vi.fn();
namespaceMocks.provider.onDidRegisterContainerConnection = vi.fn();
namespaceMocks.provider.onDidSetConnectionFactory = vi.fn();
namespaceMocks.provider.onDidUnsetConnectionFactory = vi.fn();
namespaceMocks.provider.getConnectionFactories = vi.fn();
namespaceMocks.provider.getContainerConnections = vi.fn();
namespaceMocks.provider.getInferenceConnections = vi.fn();
namespaceMocks.provider.getRagConnections = vi.fn();
namespaceMocks.provider.getProviderLifecycleContext = vi.fn();
namespaceMocks.provider.createImageFilesProvider = vi.fn();
namespaceMocks.proxy = {};
namespaceMocks.proxy.getProxySettings = vi.fn();
namespaceMocks.proxy.setProxy = vi.fn();
namespaceMocks.proxy.onDidUpdateProxy = vi.fn();
namespaceMocks.proxy.isEnabled = vi.fn();
namespaceMocks.proxy.onDidStateChange = vi.fn();
namespaceMocks.registry = {};
namespaceMocks.registry.registerRegistryProvider = vi.fn();
namespaceMocks.registry.registerRegistry = vi.fn();
namespaceMocks.registry.unregisterRegistry = vi.fn();
namespaceMocks.registry.suggestRegistry = vi.fn();
namespaceMocks.registry.onDidRegisterRegistry = vi.fn();
namespaceMocks.registry.onDidUpdateRegistry = vi.fn();
namespaceMocks.registry.onDidUnregisterRegistry = vi.fn();
namespaceMocks.mcpRegistry = {};
namespaceMocks.mcpRegistry.registerRegistryProvider = vi.fn();
namespaceMocks.mcpRegistry.registerRegistry = vi.fn();
namespaceMocks.mcpRegistry.unregisterRegistry = vi.fn();
namespaceMocks.mcpRegistry.suggestRegistry = vi.fn();
namespaceMocks.mcpRegistry.onDidRegisterRegistry = vi.fn();
namespaceMocks.mcpRegistry.onDidUpdateRegistry = vi.fn();
namespaceMocks.mcpRegistry.onDidUnregisterRegistry = vi.fn();
namespaceMocks.mcpRegistry.registerServer = vi.fn();
namespaceMocks.mcpRegistry.unregisterServer = vi.fn();
namespaceMocks.tray = {};
namespaceMocks.tray.registerMenuItem = vi.fn();
namespaceMocks.tray.registerProviderMenuItem = vi.fn();
namespaceMocks.configuration = {};
namespaceMocks.configuration.getConfiguration = vi.fn();
namespaceMocks.configuration.onDidChangeConfiguration = vi.fn();
namespaceMocks.fs = {};
namespaceMocks.fs.createFileSystemWatcher = vi.fn();
namespaceMocks.window = {};
namespaceMocks.window.showInformationMessage = vi.fn();
namespaceMocks.window.showWarningMessage = vi.fn();
namespaceMocks.window.showErrorMessage = vi.fn();
namespaceMocks.window.withProgress = vi.fn();
namespaceMocks.window.showNotification = vi.fn();
namespaceMocks.window.createStatusBarItem = vi.fn();
namespaceMocks.window.showInputBox = vi.fn();
namespaceMocks.window.showOpenDialog = vi.fn();
namespaceMocks.window.showSaveDialog = vi.fn();
namespaceMocks.window.showQuickPick = vi.fn();
namespaceMocks.window.createCustomPick = vi.fn();
namespaceMocks.window.createWebviewPanel = vi.fn();
namespaceMocks.window.listWebviews = vi.fn();
namespaceMocks.kubernetes = {};
namespaceMocks.kubernetes.getKubeconfig = vi.fn();
namespaceMocks.kubernetes.onDidUpdateKubeconfig = vi.fn();
namespaceMocks.kubernetes.setKubeconfig = vi.fn();
namespaceMocks.kubernetes.createResources = vi.fn();
namespaceMocks.kubernetes.registerKubernetesGenerator = vi.fn();
namespaceMocks.containerEngine = {};
namespaceMocks.containerEngine.listContainers = vi.fn();
namespaceMocks.containerEngine.inspectContainer = vi.fn();
namespaceMocks.containerEngine.createContainer = vi.fn();
namespaceMocks.containerEngine.startContainer = vi.fn();
namespaceMocks.containerEngine.logsContainer = vi.fn();
namespaceMocks.containerEngine.statsContainer = vi.fn();
namespaceMocks.containerEngine.stopContainer = vi.fn();
namespaceMocks.containerEngine.deleteContainer = vi.fn();
namespaceMocks.containerEngine.buildImage = vi.fn();
namespaceMocks.containerEngine.saveImage = vi.fn();
namespaceMocks.containerEngine.listImages = vi.fn();
namespaceMocks.containerEngine.tagImage = vi.fn();
namespaceMocks.containerEngine.pushImage = vi.fn();
namespaceMocks.containerEngine.pullImage = vi.fn();
namespaceMocks.containerEngine.deleteImage = vi.fn();
namespaceMocks.containerEngine.getImageInspect = vi.fn();
namespaceMocks.containerEngine.info = vi.fn();
namespaceMocks.containerEngine.listInfos = vi.fn();
namespaceMocks.containerEngine.onEvent = vi.fn();
namespaceMocks.containerEngine.listNetworks = vi.fn();
namespaceMocks.containerEngine.createNetwork = vi.fn();
namespaceMocks.containerEngine.listVolumes = vi.fn();
namespaceMocks.containerEngine.createVolume = vi.fn();
namespaceMocks.containerEngine.deleteVolume = vi.fn();
namespaceMocks.containerEngine.createPod = vi.fn();
namespaceMocks.containerEngine.replicatePodmanContainer = vi.fn();
namespaceMocks.containerEngine.startPod = vi.fn();
namespaceMocks.containerEngine.listPods = vi.fn();
namespaceMocks.containerEngine.stopPod = vi.fn();
namespaceMocks.containerEngine.removePod = vi.fn();
namespaceMocks.containerEngine.inspectPod = vi.fn();
namespaceMocks.containerEngine.createManifest = vi.fn();
namespaceMocks.containerEngine.inspectManifest = vi.fn();
namespaceMocks.containerEngine.pushManifest = vi.fn();
namespaceMocks.containerEngine.removeManifest = vi.fn();
namespaceMocks.authentication = {};
namespaceMocks.authentication.getSession = vi.fn();
namespaceMocks.authentication.onDidChangeSessions = vi.fn();
namespaceMocks.authentication.registerAuthenticationProvider = vi.fn();
namespaceMocks.env = {};
namespaceMocks.env.appName = vi.fn();
namespaceMocks.env.isMac = vi.fn();
namespaceMocks.env.isWindows = vi.fn();
namespaceMocks.env.isLinux = vi.fn();
namespaceMocks.env.isTelemetryEnabled = vi.fn();
namespaceMocks.env.onDidChangeTelemetryEnabled = vi.fn();
namespaceMocks.env.openExternal = vi.fn();
namespaceMocks.env.createTelemetryLogger = vi.fn();
namespaceMocks.env.clipboard = vi.fn();
namespaceMocks.process = {};
namespaceMocks.process.exec = vi.fn();
namespaceMocks.context = {};
namespaceMocks.context.setValue = vi.fn();
namespaceMocks.cli = {};
namespaceMocks.cli.createCliTool = vi.fn();
namespaceMocks.cli.getCliTool = vi.fn();
namespaceMocks.cli.all = vi.fn();
namespaceMocks.cli.onDidChange = vi.fn();
namespaceMocks.imageChecker = {};
namespaceMocks.imageChecker.registerImageCheckerProvider = vi.fn();
namespaceMocks.net = {};
namespaceMocks.net.getFreePort = vi.fn();
namespaceMocks.navigation = {};
namespaceMocks.navigation.navigateToDashboard = vi.fn();
namespaceMocks.navigation.navigateToContainers = vi.fn();
namespaceMocks.navigation.navigateToContainer = vi.fn();
namespaceMocks.navigation.navigateToContainerLogs = vi.fn();
namespaceMocks.navigation.navigateToContainerInspect = vi.fn();
namespaceMocks.navigation.navigateToContainerTerminal = vi.fn();
namespaceMocks.navigation.navigateToImages = vi.fn();
namespaceMocks.navigation.navigateToImageBuild = vi.fn();
namespaceMocks.navigation.navigateToImage = vi.fn();
namespaceMocks.navigation.navigateToVolumes = vi.fn();
namespaceMocks.navigation.navigateToVolume = vi.fn();
namespaceMocks.navigation.navigateToPods = vi.fn();
namespaceMocks.navigation.navigateToPod = vi.fn();
namespaceMocks.navigation.navigateToCliTools = vi.fn();
namespaceMocks.navigation.navigateToContribution = vi.fn();
namespaceMocks.navigation.navigateToWebview = vi.fn();
namespaceMocks.navigation.navigateToAuthentication = vi.fn();
namespaceMocks.navigation.navigateToResources = vi.fn();
namespaceMocks.navigation.navigateToEditProviderContainerConnection = vi.fn();
namespaceMocks.navigation.navigateToCreateProviderConnection = vi.fn();
namespaceMocks.navigation.navigateToOnboarding = vi.fn();
namespaceMocks.navigation.navigateToExtensionsCatalog = vi.fn();
namespaceMocks.navigation.register = vi.fn();
namespaceMocks.navigation.navigate = vi.fn();
namespaceMocks.rag = {};
namespaceMocks.rag.registerChunkProvider = vi.fn();

const classesMocks = {} as Record<string, unknown>;
const DisposableInstance: Record<string, unknown> = {};
DisposableInstance.dispose = vi.fn();
DisposableInstance.create = vi.fn();
DisposableInstance.from = vi.fn();
classesMocks.Disposable = DisposableInstance;
const EventEmitterInstance: Record<string, unknown> = {};
EventEmitterInstance.fire = vi.fn();
EventEmitterInstance.dispose = vi.fn();
classesMocks.EventEmitter = EventEmitterInstance;
const CancellationTokenSourceInstance: Record<string, unknown> = {};
CancellationTokenSourceInstance.cancel = vi.fn();
CancellationTokenSourceInstance.dispose = vi.fn();
classesMocks.CancellationTokenSource = CancellationTokenSourceInstance;
const UriInstance: Record<string, unknown> = {};
UriInstance.parse = vi.fn();
UriInstance.file = vi.fn();
UriInstance.joinPath = vi.fn();
UriInstance.with = vi.fn();
UriInstance.toString = vi.fn();
classesMocks.Uri = UriInstance;
const TelemetryTrustedValueInstance: Record<string, unknown> = {};
classesMocks.TelemetryTrustedValue = TelemetryTrustedValueInstance;
const RepositoryInfoParserInstance: Record<string, unknown> = {};
classesMocks.RepositoryInfoParser = RepositoryInfoParserInstance;

const eventEmitterListeners: Array<(data: unknown) => unknown> = [];
beforeEach(() => {
  eventEmitterListeners.length = 0;
});
class EventEmitter {
  event(callback: (e: unknown) => unknown): void {
    eventEmitterListeners.push(callback);
  }
  fire(data: unknown): void {
    for (const listener of eventEmitterListeners) {
      listener(data);
    }
  }
  dispose(): void {}
}
EventEmitter.prototype.dispose = vi.fn();

// Normalize env mock
if (!namespaceMocks.env) namespaceMocks.env = {};
namespaceMocks.env.isWindows = false;
namespaceMocks.env.isMac = false;
namespaceMocks.env.isLinux = false;
namespaceMocks.env.appName = product.name;

const extensionAPI = {
  ...namespaceMocks,
  ...classesMocks,
  EventEmitter,
  ProgressLocation: { APP_ICON: 1, TASK_WIDGET: 2 },
  StatusBarAlignLeft: 'LEFT',
  StatusBarAlignRight: 'RIGHT',
  StatusBarItemDefaultPriority: 0,
  InputBoxValidationSeverity: { Info: 1, Warning: 2, Error: 3 },
  QuickPickItemKind: { Separator: -1, Default: 0 },
};

module.exports = extensionAPI;
