/**********************************************************************
 * Copyright (C) 2025-2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

import type { ZodType } from 'zod';
import z from 'zod';

/**
 * Zod schema for validating AI-generated parameters
 */
export const FlowParameterSchema = z.object({
  name: z.string().describe('Parameter name (must be valid identifier)'),
  format: z.string().default('string').describe('Parameter data type'),
  description: z.string().describe('Human-readable description of the parameter'),
  default: z.string().optional().describe('Default value for the parameter'),
  // Note: 'required' is computed dynamically based on whether 'default' exists
});

/**
 * Parameter type as generated by AI
 */
export type FlowParameterAIGenerated = z.output<typeof FlowParameterSchema>;

/**
 * Full parameter type with 'required' field computed based on whether 'default' exists
 */
export type FlowParameter = FlowParameterAIGenerated & {
  required: boolean;
};

/**
 * Parameters for the detect flow fields request
 */
export interface DetectFlowFieldsParams {
  chatId?: string; // Optional - if provided, analyzes chat + prompt; if not, analyzes prompt only
  prompt: string;
  providerId: string;
  connectionName: string;
  modelId: string;
}

/**
 * Result of the detect flow fields operation
 */
export interface DetectFlowFieldsResult {
  prompt: string;
  parameters: Array<FlowParameter>;
}

/**
 * Schema for AI-generated detect flow fields result
 */
export const DetectFlowFieldsResultSchema: ZodType<
  Omit<DetectFlowFieldsResult, 'parameters'> & {
    parameters: Array<FlowParameterAIGenerated>;
  }
> = z.object({
  prompt: z
    .string()
    .describe(
      'The updated prompt with parameter placeholders using {{parameterName}} syntax. Replace specific values from the conversation with appropriate parameter names.',
    ),
  parameters: z
    .array(FlowParameterSchema)
    .describe(
      'Array of parameters detected from the conversation. Each parameter should have a name matching a {{placeholder}} in the prompt, a description, and a default value if one was found in the conversation.',
    ),
});
